name: alex_final_project
description: "Bazar APP."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  envied: ^1.3.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  flutter_screenutil: ^5.9.3
#  http_certificate_pinning: ^3.0.1
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable:
  build_runner: ^2.9.0
  flutter_lints: ^5.0.0
  envied_generator: ^1.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/cert/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700



